spring:
  application:
    name: eureka-feign-upload-client

server:
  port: 2002

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      # 多注册中心注册http://peer1:1001/eureka/,http://peer2:1002/eureka/
      defaultZone: http://localhost:1001/eureka/

logging:
  file: ${spring.application.name}.log
