spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenlong220192/spring-cloud-config-repo.git
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录
#          username:
#          password:

server:
  port: 1010
