spring:
  application:
    name: eureka-consumer-feign

server:
  port: 1006

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      # 多注册中心注册http://peer1:1001/eureka/,http://peer2:1002/eureka/
      defaultZone: http://localhost:1001/eureka/

logging:
  level:
    root: debug
    site.mingsha: debug
  file: ./logs/${spring.application.name}.log
